version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: energy_db
    environment:
      POSTGRES_DB: energy_environmental_db
      POSTGRES_USER: energy_user
      POSTGRES_PASSWORD: energy_pass_2025
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cleaned_data:/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U energy_user -d energy_environmental_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
